services:
  mysql:
    image: mysql:8.0
    container_name: laravel_mysql_practice
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3308:3306"
    volumes:
      - mysql_data_practice:/var/lib/mysql

  laravel:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: laravel_app_practice
    restart: always
    ports:
      - "8001:80"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react_app_practice
    restart: always
    ports:
      - "3002:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  mysql_data_practice: